version: "3.6"

services:
  react:
    build: .
    image: react-docker-image-green
    container_name: react-docker-green
    ports:
      - "3000:3000"
      # - "3001:3001"
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
