version: '3.6'

services:
  doeng:
    build:
      context: ./doeng
      args:
        port: 8200
    image: doeng-springboot-image-green
    container_name: doeng-springboot-green
    ports:
      - '8201:8200'
  doengFlux:
    build:
      context: ./doEngGameFlux
      args:
        port: 8000
    image: doeng-flux-image-green
    container_name: doeng-flux-green
    ports:
      - '8001:8000'
  doengAi:
    build:
      context: ./ai
      args:
        port: 9000
    image: doeng-ai-image-green
    container_name: doeng-ai-green
    ports:
      - '9001:9000'
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
