version: '3.6'

services:
  doeng:
    build:
      context: ./doeng
    image: doeng-springboot-image-blue
    container_name: doeng-springboot-blue
    ports:
      - '8200:8200'
  doengFlux:
    build:
      context: ./doEngGameFlux
    image: doeng-flux-image-blue
    container_name: doeng-flux-blue
    ports:
      - '8000:8000'
  doengAi:
    build:
      context: ./ai
    image: doeng-ai-image-blue
    container_name: doeng-ai-blue
    ports:
      - '9000:9000'
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
